#ifndef __PGTK_ERRORS_H__
#define __PGTK_ERRORS_H__

#define PGTK_ERRNO_NONE 0i32

#define PGTK_ERRNO_MALLOC 1i32

#define PGTK_ERRNO_STB 2i32

#define PGTK_ERRNO_ENCODING_HC 3i32

#define PGTK_ERRNO_ENCODING_SIZE 4i32

#define PGTK_ERRNO_IMAGE_SCALE 5i32

#define PGTK_ERRNO_INVALID_IMAGE 6i32

#endif