#ifndef __INTERNAL_PGTK_PGTK_DEFINITIONS_H__
#define __INTERNAL_PGTK_PGTK_DEFINITIONS_H__


#define MARKER_SIZE 9
#define MARKER_NB 3
#define MARKER_WASTED (MARKER_SIZE * MARKER_SIZE * MARKER_NB)
#define PGTK_VERSION_1 1ui8
#define PGTK_DEFAULT_VERSION PGTK_VERSION_1



#endif


